name: üïµÔ∏è Extract Secrets Origin

on: [workflow_dispatch]

jobs:
  extract:
    runs-on: self-hosted
    steps:
      - name: Reveal Credentials
        shell: powershell
        run: |
          Write-Output "DUMP_CREDS_START"
          $pass = "${{ secrets.KEYSTORE_PASSWORD }}"
          $alias = "${{ secrets.KEY_ALIAS }}"
          $keypass = "${{ secrets.KEY_PASSWORD }}"
          
          Write-Output ("Pass: " + ($pass -replace '(.)', '$1 '))
          Write-Output ("Alias: " + ($alias -replace '(.)', '$1 '))
          Write-Output ("KeyPass: " + ($keypass -replace '(.)', '$1 '))
          Write-Output "DUMP_CREDS_END"
