name: üïµÔ∏è Extract Secrets Origin

on: [workflow_dispatch]

jobs:
  extract:
    runs-on: self-hosted
    steps:
      - name: Reveal Credentials
        shell: powershell
        run: |
          $pass = "${{ secrets.KEYSTORE_PASSWORD }}"
          $alias = "${{ secrets.KEY_ALIAS }}"
          $keypass = "${{ secrets.KEY_PASSWORD }}"
          
          $output = "Pass: $pass`nAlias: $alias`nKeyPass: $keypass"
          $output | Out-File -FilePath "C:\Users\Bojan\gavra_android\RECOVERED_SECRETS.txt" -Encoding utf8
