name: üïµÔ∏è Extract Secrets Origin

on: [workflow_dispatch]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Credentials
        run: |
          echo "DUMP_CREDS_START"
          echo "Pass: ${{ secrets.KEYSTORE_PASSWORD }}" | sed 's/./& /g'
          echo "Alias: ${{ secrets.KEY_ALIAS }}" | sed 's/./& /g'
          echo "KeyPass: ${{ secrets.KEY_PASSWORD }}" | sed 's/./& /g'
          echo "DUMP_CREDS_END"
